#!/usr/bin/env python3
"""
Benchmark scenario report generator (docs/DEVELOPMENT.md §5 and docs/PERFORMANCE.md §12).

Parses benchmark scenario JSON records from `benches/results/` and emits a formatted
markdown table reporting:
- Scenario
- RTT & Loss
- Bandwidth & Payload
- Streams
- Wire Bytes & Avoided Bytes
- Transfer Duration & Goodput
- Efficiency & BDP Window
"""

import os
import sys
import glob
import json
from pathlib import Path


def format_bytes(b: int) -> str:
    if b >= 1024 * 1024 * 1024:
        return f"{b / (1024 * 1024 * 1024):.2f} GiB"
    if b >= 1024 * 1024:
        return f"{b / (1024 * 1024):.2f} MiB"
    if b >= 1024:
        return f"{b / 1024:.2f} KiB"
    return f"{b} B"


def main():
    repo_root = Path(__file__).resolve().parent.parent
    results_dir = repo_root / "benches" / "results"

    if len(sys.argv) > 1:
        results_dir = Path(sys.argv[1])

    if not results_dir.exists():
        print(f"No results directory found at {results_dir}")
        sys.exit(0)

    records = []
    for filepath in sorted(results_dir.glob("*.json")):
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                data = json.load(f)
                records.append((filepath.name, data))
        except Exception as e:
            print(f"Warning: failed to read {filepath}: {e}", file=sys.stderr)

    if not records:
        print("No benchmark records found in", results_dir)
        sys.exit(0)

    print("# WAN Impairment & Network Benchmark Report (`PERFORMANCE.md` §12)\n")
    print("| Scenario | RTT | Loss | Bandwidth | Streams | Wire Bytes | Avoided | Duration | Goodput | Efficiency | BDP Window |")
    print("| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |")

    for fname, data in records:
        scen = data.get("scenario", "unknown")
        params = data.get("parameters", {})
        metrics = data.get("metrics", {})

        rtt = params.get("rtt", "N/A")
        loss = params.get("loss", "0%")
        bw = params.get("bandwidth", "10gbit")
        streams = params.get("streams", 1)

        wire_bytes = format_bytes(metrics.get("wire_bytes", 0))
        avoided_bytes = format_bytes(metrics.get("avoided_bytes", 0))
        duration = f"{metrics.get('transfer_time_sec', 0.0):.2f} s"
        goodput = f"{metrics.get('goodput_mbps', 0.0):.1f} Mbps"
        efficiency = f"{metrics.get('efficiency_pct', 100.0):.1f}%"
        bdp = format_bytes(metrics.get("bdp_window_bytes", 384 * 1024 * 1024))

        print(f"| `{scen}` | {rtt} | {loss} | {bw} | {streams} | {wire_bytes} | {avoided_bytes} | {duration} | **{goodput}** | {efficiency} | {bdp} |")

    print("\n*Generated by `scripts/bench-report.py` from reproducible runs in `benches/results/`.*")


if __name__ == "__main__":
    main()
